---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - food.tacos.io
  resources:
  - tacoorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - food.tacos.io
  resources:
  - tacoorders/finalizers
  verbs:
  - update
- apiGroups:
  - food.tacos.io
  resources:
  - tacoorders/status
  verbs:
  - get
  - patch
  - update
