# permissions for end users to edit tacoorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: taco-operator
    app.kubernetes.io/managed-by: kustomize
  name: tacoorder-editor-role
rules:
- apiGroups:
  - food.tacos.io
  resources:
  - tacoorders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - food.tacos.io
  resources:
  - tacoorders/status
  verbs:
  - get
