services:
  notifications:
    build:
      context: .
      dockerfile: ./cmd/notifications/Dockerfile
    ports:
      - 8091:8091
    networks:
      - bad_inc_net
  users:
    build:
      context: .
      target: final
      dockerfile: ./cmd/users/Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - bad_inc_net
  nemesis:
    build:
      context: .
      dockerfile: ./cmd/nemesis/Dockerfile
    ports:
      - 50051:50051
    networks:
      - bad_inc_net
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bad_inc_net

  rabbitMq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - bad_inc_net

  kong-database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-database:/var/lib/postgresql/data
    networks:
      - bad_inc_net

  kong-migration:
    image: kong:latest
    restart: on-failure
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    command: ["kong", "migrations", "bootstrap"]
    networks:
      - bad_inc_net

  kong:
    image: kong:latest
    restart: always
    depends_on:
      - kong-database
      - kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - bad_inc_net

volumes:
  kong-database:
  mongo_data:

networks:
  bad_inc_net:
    driver: bridge
