apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taco-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taco-operator
  endpoints:
    - port: "8443"
      interval: 10s
